apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    module: donor
    app: redcross345-customer
spec:
  selector:
    matchLabels:
      app: redcross345-customer
      # module: donor
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: redcross345-customer
        module: donor
    spec:     # pod spec
      containers: 
      - name: frontend
        ports:
        - containerPort: 10
          $patch: delete
        - containerPort: 80  
        env:
        - name: PORT_VALUE
          value: "80"  
        - name: DATABASE_NAME
          value: "redcross345"    
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: redcross345-customer
spec:
  selector:
    app: redcross345-customer
  ports:
    - port: 8080
      $patch: delete
      targetPort: 10
      $patch: delete
    - port: 8081
      targetPort: 80  


---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-vs
spec:
  hosts:
  #   - abc.sreyo.in
  #     $patch: delete
    # - def.sreyo.in  
    - redcross345-api.sreyo.in
  http:
    - route:
        - destination:
            # host: frontend-service.default.svc.cluster.local
            # $patch: delete
            # host: test-frontend-service.default.svc.cluster.local
            host: redcross345-frontend-service.default.svc.cluster.local
            port:
              # number: 8081  
              # $patch: delete 
              number: 8081
