name: Delete database

on:
  workflow_dispatch
  # repository_dispatch:
  #   types: [delete]


env:
  DB_CONNECTION: mongodb+srv://Test:1234@cluster0.cusya.mongodb.net/
  DB_NAME: redcross
  # DEPLOYMENT: "${{ github.event.client_payload.customer_name}}-frontend-deployment"

jobs:
 Job1: 
    name: Delete db dynamically
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

          
    # connect to mongo and delete db
    - name: connect to MongoDB Atlas
      run: |-
        mongosh $DB_CONNECTION
        use redcross
        db.dropDatabase()

    # # delete db
    # - name: Delete customer database
    #   run: |-
    #     use $DB_NAME
    #     db.dropDatabase()



      
